### PR TITLE
extraction of functions from mgDb-class

### PR DESCRIPTION
**Pull request by daniel01001000**
2016-06-06 
Pull request for extraction of functions from the mgDb-class

### CODE REVIEW

**Comment by jnpaulson** [comment]
Hi there - nice commit. Please check out the failing checks. FYI this is not the Bioconductor version and we need to merge the two.

**Comment by nate-d-olson** [comment]
Daniel, to address the build error please add the new files to the DESCRIPTION file under collate. Also, go ahead and remove 20160606-functionextract.md as it is not part of the package.

**Comment by daniel01001000** [comment]
Sorry about that. I updated the DESCRIPTION file and removed the markdown
file.

-Daniel

**Comment by nate-d-olson** [comment]
Nice work Daniel!

**Pull request merged**
